language: node_js
node_js: '14.1.0'
os: linux

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta
    # - ATOM_CHANNEL=dev

addons:
  apt:
    packages:
      - build-essential
      - fakeroot
      - git
      - libsecret-1-dev

before_script:
  - nvm use
  - npm install
  - npm run parse

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

git:
  depth: 10

sudo: false

notifications:
  email:
    on_success: change
    on_failure: change
