language: node_js
node_js: '10.13.0'
os: linux

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta
    - ATOM_CHANNEL=dev

addons:
  apt:
    packages:
      - build-essential
      - fakeroot
      - git
      - libsecret-1-dev

before_script:
  - npm install
  - npm run parse

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh
  # CI gem test
  - sudo gem install github_changelog_generator

git:
  depth: 10

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change
