name: Atomforce CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: [macOS-latest, ubuntu-latest, windows-latest]

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1,
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies & parse all files
      run: |
        npm i
        npm run lint:fix && npm run lint
      env:
        CI: true
